name: CI/CD for Image Recognition

on:
  push:
<<<<<<< HEAD
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
=======
    branches: [ Unit-Testing ]
  pull_request:
    branches: [ Unit-Testing ]
>>>>>>> 6769210b803f0a51261018c4ad5a98025586bcef

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision opencv-python pytest Pillow

    - name: Run Unit Tests
      run: |
        pytest
