name: CI/CD for Image Recognition

on:
  push:
    branches: [ Unit-Testing_2 ]
  pull_request:
    branches: [ Unit-Testing_2 ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision opencv-python pytest Pillow requests numpy matplotlib scipy pandas tqdm ultralytics pyyaml

    - name: Run Unit Tests
      run: |
        pytest -s
